### ISSUE TITLE
Electron packaging build (`next build` / `electron:make`) is broken on clean CI — all platforms

### ISSUE THREAD

**Issue by hilash** [hilash/cabinet#141]
## Summary

`npm run electron:make:win` (and by extension the macOS `electron:make`) **fails on a clean checkout / CI runner**, independent of platform. Surfaced while validating the Windows packaging gate (#94 §10) for #139. None of this is caused by #139 — it's pre-existing on `main`. The packaged Electron app therefore cannot currently be built in CI.

The failure is a **chain** inside `next build`:

### 1. `mcps/mcp-discord` type-check — FIXED in #139
`next build` type-checks `**/*.ts` repo-wide, pulling in `mcps/mcp-discord/src/discord.ts`. That sub-package's deps (`discord.js`) aren't installed by a root-only `npm ci`, so a clean run failed with `Cannot find module 'discord.js'`. Fixed by excluding `mcps` from `tsconfig.json` (matching the existing `cabinetai`/`cli` exclusions). ✅

### 2. `/login` — `useSearchParams()` without Suspense — STILL BROKEN
```
⨯ useSearchParams() should be wrapped in a suspense boundary at page "/login".
Error occurred prerendering page "/login". ... Export encountered an error on /login/page: /login, exiting the build.
```
`src/app/login/page.tsx:10` calls `useSearchParams()` at the page top level. With `output: "standalone"`, `next build` prerenders the page and bails. **Fix:** move the `useSearchParams` usage into a child component wrapped in `<Suspense>`. It's the only page using `useSearchParams`, so this is the only offender of this kind.

### 3. `electron-forge make` / Squirrel installer — UNPROVEN (the actual #94 §10 gate)
The build has never reached this step on Windows CI, so whether the Squirrel `.exe` / ZIP actually packages is still unverified.

## Evidence
- Failed runs on `fix/windows-cli-and-polish` (validate mode, macOS job skipped):
  - Run 27517888282 — failed at #1 (mcps/discord.js)
  - Run 27518210046 — got past #1, failed at #2 (/login)

## How to reproduce locally
`rm -rf node_modules && npm ci && npm run build` from a clean tree (do **not** pre-install `mcps/*/node_modules`).

## Suggested next steps
1. Wrap `/login`'s `useSearchParams` in `<Suspense>`.
2. Re-run the Windows packaging via the new validate mode: `gh workflow run electron-release.yml --ref <branch>` (no tag → builds the branch, uploads ZIP+Squirrel as an artifact, no release writes — added in #139).
3. Fix whatever `electron-forge make` surfaces next; that's the real #94 §10 gate.
